
```{r}
# 1. Create variables with all atomic types
character_var <- "Hello, R!"
numeric_var <- 3.14
integer_var <- 42L
complex_var <- 2 + 3i
logical_var <- TRUE
```

```{r}
# 2. Create vectors
# * Sequence from 5 to 75
sequence_vector <- seq(5, 75)

# * Numbers: 3.14, 2.71, 0, 13
numbers_vector <- c(3.14, 2.71, 0, 13)

# * With 100 TRUE values
true_vector <- rep(TRUE, 100)
```

```{r}
# 3. Create matrix
my_matrix <- matrix(c(12, 34, 87, -12, -12.1, 0, 3.6, 0.5, 1.3), nrow = 3, ncol = 3)
```

```{r}
# 4. Create a list with all atomic types
my_list <- list(character_var, numeric_var, integer_var, complex_var, logical_var)
```

```{r}
# 5. Create a factor with 3 levels: infant, child, adult
age_factor <- factor(c("infant", "child", "adult", "child", "adult"), levels = c("infant", "child", "adult"))

```

```{r}
# 6. Create a data frame
data_frame <- data.frame(Name = c("John", "Jane", "Tom"),
                         Age = c(25, 30, 22),
                         Score = c(88.5, 92.3, 84.7))
```


```{r}
# 7. Change column names of the data frame
colnames(data_frame) <- c("Person", "Years", "Grade")

# Display results
print(character_var)
print(numeric_var)
print(integer_var)
print(complex_var)
print(logical_var)

print(sequence_vector)
print(numbers_vector)
print(true_vector)

print(my_matrix)
print(my_list)
print(age_factor)
print(data_frame)

```

